# Generated by Django 5.0.4 on 2024-04-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
