# Generated by Django 5.0.4 on 2024-04-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
