# Generated by Django 5.0.4 on 2024-04-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
    ]
