# Generated by Django 5.0.4 on 2024-04-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobapplication_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applicant',
        ),
    ]
